# See https://pre-commit.com/hooks.html for info on hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # frozen: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 2ddea293a88919650266472186620a98a4a8bb37  # frozen: 22.12.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: c838a5e98878f17889cfce311e1406d252f87ec5  # frozen: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88]

  - repo: https://github.com/PyCQA/isort
    rev: dbf82f2dd09ae41d9355bcd7ab69187a19e6bf2f  # frozen: 5.12.0
    hooks:
      - id: isort
