# See https://pre-commit.com/hooks.html for info on hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # frozen: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 6fdf8a4af28071ed1d079c01122b34c5d587207a  # frozen: 24.2.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7d37d9032d0d161634be4554273c30efd4dea0b3  # frozen: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88]

  - repo: https://github.com/PyCQA/isort
    rev: c235f5e450b4b84e58d114ed4c589cbf454175a3  # frozen: 5.13.2
    hooks:
      - id: isort
